/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Metallic Artisan (Oat Edition) - Stitch Design System
        "on-surface": "#1b1b1c",
        "on-surface-variant": "#4d453f",
        "background": "#fcf9f8",
        "surface": "#fcf9f8",
        "surface-bright": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "surface-container-high": "#eae7e7",
        "surface-container-highest": "#e5e2e1",
        "surface-variant": "#e5e2e1",
        "on-background": "#1b1b1c",
        "primary": "#463f38",
        "on-primary": "#ffffff",
        "primary-container": "#5e564f",
        "on-primary-container": "#d7ccc3",
        "primary-fixed": "#ece0d7",
        "primary-fixed-dim": "#d0c4bc",
        "on-primary-fixed": "#201b15",
        "on-primary-fixed-variant": "#4d453f",
        "secondary": "#5e5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e3e2e2",
        "on-secondary-container": "#646464",
        "secondary-fixed": "#e3e2e2",
        "secondary-fixed-dim": "#c7c6c6",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#464747",
        "tertiary": "#4c3e25",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#65553a",
        "on-tertiary-container": "#e0cba8",
        "tertiary-fixed": "#f6dfbc",
        "tertiary-fixed-dim": "#d9c4a2",
        "on-tertiary-fixed": "#251a05",
        "on-tertiary-fixed-variant": "#53452b",
        "outline": "#7e766e",
        "outline-variant": "#cfc5bc",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#d0c4bc",
        "surface-tint": "#655d56",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "serif": ["Noto Serif", "serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [],
}
